#define bilang std::cout
#define sudah std::endl
#define gabung <<
#define masukan >>
#define minta std::cin
#define var int
#define let float
#define Constanta const
#define Strings string
#define bantu system